In [1]:
pwd

'/Users/gerardfullsack/Desktop/SF-Restaurant-Yelp-and-Health-Score'

In [2]:
import pandas as pd
from sqlalchemy import create_engine
import json
from pymongo import MongoClient

In [3]:
client = MongoClient('localhost', 27017)
db = client['SF_Restaurant_db']

In [4]:
csv_file = "Resources/SF_restaurant_scores_lives_standard.csv"
Restaurant_health_data_df = pd.read_csv(csv_file)
Restaurant_health_data_df.head()

,business_id,business_name,business_address,business_city,business_state,business_postal_code,business_latitude,business_longitude,business_location,business_phone_number,...,inspection_type,violation_id,violation_description,risk_category,Neighborhoods,Police Districts,Supervisor Districts,Fire Prevention Districts,Zip Codes,Analysis Neighborhoods
0,97975,BREADBELLY,1408 Clement St,San Francisco,CA,94118,NaN,NaN,NaN,1.415724e+10,...,Routine - Unscheduled,97975_20190725_103124,Inadequately cleaned or sanitized food contact...,Moderate Risk,NaN,NaN,NaN,NaN,NaN,NaN
1,69487,Hakkasan San Francisco,1 Kearny St,San Francisco,CA,94108,NaN,NaN,NaN,NaN,...,Routine - Unscheduled,69487_20180418_103119,Inadequate and inaccessible handwashing facili...,Moderate Risk,NaN,NaN,NaN,NaN,NaN,NaN
2,91044,Chopsticks Restaurant,4615 Mission St,San Francisco,CA,94112,NaN,NaN,NaN,NaN,...,Non-inspection site visit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,85987,Tselogs,552 Jones St,San Francisco,CA,94102,NaN,NaN,NaN,NaN,...,Routine - Unscheduled,85987_20180412_103132,Improper thawing methods,Moderate Risk,NaN,NaN,NaN,NaN,NaN,NaN
4,96024,Fig & Thistle Market,691 14th St,San Francisco,CA,94114,NaN,NaN,NaN,NaN,...,New Ownership - Followup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
health_data_df = Restaurant_health_data_df[['business_id', 'business_name','business_city','inspection_score', 'inspection_date']].copy()
health_data_df.head()

,business_id,business_name,business_city,inspection_score,inspection_date
0,97975,BREADBELLY,San Francisco,96.0,2019-07-25T00:00:00.000
1,69487,Hakkasan San Francisco,San Francisco,88.0,2018-04-18T00:00:00.000
2,91044,Chopsticks Restaurant,San Francisco,NaN,2017-08-18T00:00:00.000
3,85987,Tselogs,San Francisco,94.0,2018-04-12T00:00:00.000
4,96024,Fig & Thistle Market,San Francisco,NaN,2018-11-08T00:00:00.000

In [6]:
#json_file = "Resources/business.json"
#Yelp_business_df = pd.read_json (json_file, lines = True )

In [7]:
#new_yelp_business_df = Yelp_business_df[["name","categories", "city","stars","state","postal_code" ]].copy()

In [8]:
#CA_yelp_business_df = new_yelp_business_df.loc[new_yelp_business_df["state"]=="CA"]
#CA_yelp_business_df.head()



#SF_restaurant_yelp_business_df = CA_yelp_business_df.loc[Restaurant_yelp_business_df["city"]=="San Francisco"]
#SF_restaurant_yelp_business_df.head()
#CA_yelp_business_df

In [9]:
csv_file = "Resources/yelp_restaurants.csv"
Restaurant_health_data_df = pd.read_csv(csv_file)
Restaurant_health_data_df.head()

,alias,categories,coordinates,display_phone,distance,id,image_url,is_closed,location,name,phone,price,rating,review_count,transactions,url
0,fog-harbor-fish-house-san-francisco-2,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...","{'latitude': 37.809041, 'longitude': -122.410233}",(415) 421-2442,5827.740044,f-m7-hyFzkf0HSEeQ2s-9A,https://s3-media1.fl.yelpcdn.com/bphoto/Lv7tIR...,False,"{'address1': 'Pier 39', 'address2': 'Ste A-202...",Fog Harbor Fish House,1.415421e+10,$$,4.0,5531,['restaurant_reservation'],https://www.yelp.com/biz/fog-harbor-fish-house...
1,the-house-san-francisco,"[{'alias': 'asianfusion', 'title': 'Asian Fusi...","{'latitude': 37.79851, 'longitude': -122.40706}",(415) 986-8612,4911.928932,ZoZjbOYR-apY8XvommlNUA,https://s3-media2.fl.yelpcdn.com/bphoto/UzrNIk...,False,"{'address1': '1230 Grant Ave', 'address2': '',...",The House,1.415987e+10,$$$,4.5,4650,['restaurant_reservation'],https://www.yelp.com/biz/the-house-san-francis...
2,marufuku-ramen-sf-san-francisco,"[{'alias': 'ramen', 'title': 'Ramen'}]","{'latitude': 37.785155, 'longitude': -122.432075}",(415) 872-9786,2724.336437,HHtpR0RslupSQ99GIIwW5A,https://s3-media2.fl.yelpcdn.com/bphoto/2lUFO5...,False,"{'address1': '1581 Webster St', 'address2': 'S...",Marufuku Ramen SF,1.415873e+10,$$,4.5,2404,[],https://www.yelp.com/biz/marufuku-ramen-sf-san...
3,beretta-san-francisco,"[{'alias': 'italian', 'title': 'Italian'}, {'a...","{'latitude': 37.75384, 'longitude': -122.42055}",(415) 695-1199,1591.309745,4KfQnlcSu4bbTqnvGdGptw,https://s3-media1.fl.yelpcdn.com/bphoto/RsCeyB...,False,"{'address1': '1199 Valencia St', 'address2': '...",Beretta,1.415695e+10,$$,4.0,3500,['restaurant_reservation'],https://www.yelp.com/biz/beretta-san-francisco...
4,farmhouse-kitchen-thai-cuisine-san-francisco,"[{'alias': 'thai', 'title': 'Thai'}, {'alias':...","{'latitude': 37.7602179, 'longitude': -122.411...",(415) 814-2920,2228.504131,8kck3-K4zYKTJbJko0JlXQ,https://s3-media3.fl.yelpcdn.com/bphoto/AC0JE-...,False,"{'address1': '710 Florida St', 'address2': '',...",Farmhouse Kitchen Thai Cuisine,1.415814e+10,$$,4.0,2034,"['pickup', 'delivery', 'restaurant_reservation']",https://www.yelp.com/biz/farmhouse-kitchen-tha...

In [ ]:
health_data_df = Restaurant_health_data_df[['business_id', 'business_name','business_city','inspection_score', 'inspection_date']].copy()
health_data_df.head()